### ISSUE TITLE
Make it so that the invoice and part pay check out pages looks the same.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#56]
![prestashop invoice](https://cloud.githubusercontent.com/assets/10434920/5874426/8a155076-a301-11e4-9403-50078e27c4cd.png)
![prestashop part pay](https://cloud.githubusercontent.com/assets/10434920/5874427/8a2f3a86-a301-11e4-9b0d-1045ea48df4b.png)

**Comment by Boxedsolutions** [comment]
Hide Right Column or find a way to show it on partpayment @andyjohansson

**Comment by andyjohansson** [comment]
Hide it.

**Comment by Boxedsolutions** [comment]
Its hidden now

**Comment by joakim-combain** [comment]
there is still a big difference between the invoice and part pay page.
![teststore1](https://cloud.githubusercontent.com/assets/10434920/5899831/a01a2a42-a561-11e4-8511-58c64a0bc68d.png)
![teststore2](https://cloud.githubusercontent.com/assets/10434920/5899840/a6d641b8-a561-11e4-8d88-89c5633157ed.png)

**Comment by Boxedsolutions** [comment]
![faktura1 4](https://cloud.githubusercontent.com/assets/8977650/5899861/060106e6-a562-11e4-99c5-14e90d0c7cdc.png)
Is it Cached?

**Comment by joakim-combain** [comment]
![prestashop invoice1](https://cloud.githubusercontent.com/assets/10434920/5899897/a93d7aa6-a562-11e4-9af4-68c63da1497b.png)
![prestashop invoice2](https://cloud.githubusercontent.com/assets/10434920/5899898/a93f478c-a562-11e4-8c66-ea9b8b15e900.png)
this is what I have in incognito. So it's hidden but the rest of the design is different for the two payment methods. Don't know if it's just the part pay logo that is huge and that's why it looks like that.

**Comment by Boxedsolutions** [comment]
@andyjohansson Which design do you prefer?

**Comment by andyjohansson** [comment]
The top one, but keep in mind the other thing I wrote about it in issue #29

**Comment by andyjohansson** [comment]
What's the status on this one @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Should fix this the next thing i do,

**Comment by Boxedsolutions** [comment]
![delbetalning](https://cloud.githubusercontent.com/assets/8977650/5908872/87a31718-a5ab-11e4-8626-9937837b989c.png)

![fakturastyle](https://cloud.githubusercontent.com/assets/8977650/5908878/8c357dac-a5ab-11e4-8d1b-0a1c24754b65.png)

I know the untranslated stuff. Will figure it out how to force translation.

**Comment by andyjohansson** [comment]
Design looks good, maybe we should add "Vänligen fyll i följande fält för att slutföra din order" to part payment as well. And it should say "Vänligen fyll i nedanstående fält för att slutföra in order".

But i now see that the padding-left for "Billmate fakturabetalning" and "Billmate Delbetalning" is not the same under "Order Summering"

We will figure out all the text tomorrow so that it says and looks the same as good as it gets.

**Comment by joakim-combain** [comment]
I'm not sure what has been said here and what things has changed. I need to know to be able to confirm that it's fixed.

**Comment by andyjohansson** [comment]
This one is not yet fixed:
"Vänligen fyll i nedanstående fält för att slutföra er order"

**Comment by andyjohansson** [comment]
Has to do with #75.
